---
serverCredentialMappings:
  - serverId: "opendaylight-staging"
    credentialsId: &cred "dummy"
  - serverId: "opendaylight-snapshot"
    credentialsId: *cred
  - serverId: "opendaylight-site"
    credentialsId: *cred
  - serverId: "ossrh"
    credentialsId: *cred
